name: Wubin Qu
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
highlighter: pygments
timezone: China/Beijing
baseurl: /
